-- AlterTable
ALTER TABLE "Banner" ADD COLUMN     "imagePositionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "imagePositionY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "imageScale" DOUBLE PRECISION NOT NULL DEFAULT 1.0;
